<?php
/**
 * Invoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wuro\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wuro API
 *
 * API de votre espace Wuro, connectez-vous sur https://wuro.pro, dans les paramètres de votre entreprise \"Développeurs (API)\", créez une application avec un scope défini afin de demander un jeton d'accès (GET accessToken) avec vos identifiants
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.17
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Wuro\Api\Model;

use \ArrayAccess;
use \Wuro\Api\ObjectSerializer;

/**
 * Invoice Class Doc Comment
 *
 * @category Class
 * @package  Wuro\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Invoice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Invoice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
'title' => 'string',
'name' => 'string',
'number' => 'string',
'date' => 'object',
'company' => 'object',
'category' => 'object',
'user' => 'object',
'currency' => 'object',
'payment_methods' => 'object',
'shipping' => 'object',
'invoice_lines' => '\Wuro\Api\Model\InvoiceLine[]',
'display_expeditor' => 'bool',
'num_tva' => 'string',
'client_code' => 'string',
'analytical_code' => 'string',
'currency_rate' => 'string',
'payment_expiry_date' => 'string',
'payment_date' => 'string',
'payment_method_name' => 'string',
'late_penalty_rate' => 'float',
'shipping_total_ht' => 'string',
'shipping_tva_rate' => 'string',
'shipping_total_tva' => 'float',
'shipping_method' => 'string',
'discount_total_ht' => 'string',
'discount_total_type' => 'string',
'total_ht_nodiscount' => 'float',
'total_ht' => 'float',
'total_ttc' => 'float',
'total_tva' => 'float',
'vat_rates' => 'object[]',
'comment' => 'string',
'notes' => 'string',
'state' => 'string',
'sale_date' => 'string',
'company_name' => 'string',
'company_contact' => 'string',
'company_siren' => 'string',
'company_nic' => 'string',
'company_share_capital' => 'float',
'company_commercial_court' => 'string',
'company_num_rcs' => 'string',
'company_num_trade_directory' => 'string',
'company_type' => 'string',
'company_address' => 'string',
'company_address_end' => 'string',
'company_zip_code' => 'string',
'company_city' => 'string',
'company_country' => 'string',
'company_phone' => 'string',
'company_fax' => 'string',
'company_email' => 'string',
'company_cgv' => 'string',
'company_include_cgv' => 'bool',
'client_name' => 'string',
'client_contact' => 'string',
'client_address' => 'string',
'client_address_end' => 'string',
'client_zip_code' => 'string',
'client_city' => 'string',
'client_country' => 'string',
'client_phone' => 'string',
'client_fax' => 'string',
'client_email' => 'string',
'client_tva' => 'string',
'client_dom' => 'bool',
'delivery_name' => 'string',
'delivery_contact' => 'string',
'delivery_address' => 'string',
'delivery_address_end' => 'string',
'delivery_zip_code' => 'string',
'delivery_city' => 'string',
'delivery_country' => 'string',
'delivery_phone' => 'string',
'delivery_fax' => 'string',
'delivery_email' => 'string',
'display_rules' => 'object',
'style' => 'object',
'has_reduction' => 'bool',
'signature' => 'object',
'external_file' => 'string',
'pdf_link' => 'string',
'external_url' => 'string',
'payment_state' => 'string',
'payments' => '\Wuro\Api\Model\Payment[][]',
'total_nettopay' => 'float',
'fromquote' => 'string',
'credit' => 'bool',
'acompte' => 'bool',
'document_model' => 'string',
'created_at' => '\DateTime',
'updated_at' => '\DateTime'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
'title' => null,
'name' => null,
'number' => null,
'date' => null,
'company' => null,
'category' => null,
'user' => null,
'currency' => null,
'payment_methods' => null,
'shipping' => null,
'invoice_lines' => null,
'display_expeditor' => null,
'num_tva' => null,
'client_code' => null,
'analytical_code' => null,
'currency_rate' => null,
'payment_expiry_date' => null,
'payment_date' => null,
'payment_method_name' => null,
'late_penalty_rate' => null,
'shipping_total_ht' => null,
'shipping_tva_rate' => null,
'shipping_total_tva' => null,
'shipping_method' => null,
'discount_total_ht' => null,
'discount_total_type' => null,
'total_ht_nodiscount' => null,
'total_ht' => null,
'total_ttc' => null,
'total_tva' => null,
'vat_rates' => null,
'comment' => null,
'notes' => null,
'state' => null,
'sale_date' => null,
'company_name' => null,
'company_contact' => null,
'company_siren' => null,
'company_nic' => null,
'company_share_capital' => null,
'company_commercial_court' => null,
'company_num_rcs' => null,
'company_num_trade_directory' => null,
'company_type' => null,
'company_address' => null,
'company_address_end' => null,
'company_zip_code' => null,
'company_city' => null,
'company_country' => null,
'company_phone' => null,
'company_fax' => null,
'company_email' => null,
'company_cgv' => null,
'company_include_cgv' => null,
'client_name' => null,
'client_contact' => null,
'client_address' => null,
'client_address_end' => null,
'client_zip_code' => null,
'client_city' => null,
'client_country' => null,
'client_phone' => null,
'client_fax' => null,
'client_email' => null,
'client_tva' => null,
'client_dom' => null,
'delivery_name' => null,
'delivery_contact' => null,
'delivery_address' => null,
'delivery_address_end' => null,
'delivery_zip_code' => null,
'delivery_city' => null,
'delivery_country' => null,
'delivery_phone' => null,
'delivery_fax' => null,
'delivery_email' => null,
'display_rules' => null,
'style' => null,
'has_reduction' => null,
'signature' => null,
'external_file' => null,
'pdf_link' => null,
'external_url' => null,
'payment_state' => null,
'payments' => null,
'total_nettopay' => null,
'fromquote' => null,
'credit' => null,
'acompte' => null,
'document_model' => null,
'created_at' => 'date',
'updated_at' => 'date'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'title' => 'title',
'name' => 'name',
'number' => 'number',
'date' => 'date',
'company' => 'company',
'category' => 'category',
'user' => 'user',
'currency' => 'currency',
'payment_methods' => 'payment_methods',
'shipping' => 'shipping',
'invoice_lines' => 'invoice_lines',
'display_expeditor' => 'display_expeditor',
'num_tva' => 'num_tva',
'client_code' => 'client_code',
'analytical_code' => 'analytical_code',
'currency_rate' => 'currency_rate',
'payment_expiry_date' => 'payment_expiry_date',
'payment_date' => 'payment_date',
'payment_method_name' => 'payment_method_name',
'late_penalty_rate' => 'late_penalty_rate',
'shipping_total_ht' => 'shipping_total_ht',
'shipping_tva_rate' => 'shipping_tva_rate',
'shipping_total_tva' => 'shipping_total_tva',
'shipping_method' => 'shipping_method',
'discount_total_ht' => 'discount_total_ht',
'discount_total_type' => 'discount_total_type',
'total_ht_nodiscount' => 'total_ht_nodiscount',
'total_ht' => 'total_ht',
'total_ttc' => 'total_ttc',
'total_tva' => 'total_tva',
'vat_rates' => 'VATRates',
'comment' => 'comment',
'notes' => 'notes',
'state' => 'state',
'sale_date' => 'sale_date',
'company_name' => 'company_name',
'company_contact' => 'company_contact',
'company_siren' => 'company_siren',
'company_nic' => 'company_nic',
'company_share_capital' => 'company_share_capital',
'company_commercial_court' => 'company_commercial_court',
'company_num_rcs' => 'company_num_rcs',
'company_num_trade_directory' => 'company_num_trade_directory',
'company_type' => 'company_type',
'company_address' => 'company_address',
'company_address_end' => 'company_address_end',
'company_zip_code' => 'company_zip_code',
'company_city' => 'company_city',
'company_country' => 'company_country',
'company_phone' => 'company_phone',
'company_fax' => 'company_fax',
'company_email' => 'company_email',
'company_cgv' => 'company_cgv',
'company_include_cgv' => 'company_include_cgv',
'client_name' => 'client_name',
'client_contact' => 'client_contact',
'client_address' => 'client_address',
'client_address_end' => 'client_address_end',
'client_zip_code' => 'client_zip_code',
'client_city' => 'client_city',
'client_country' => 'client_country',
'client_phone' => 'client_phone',
'client_fax' => 'client_fax',
'client_email' => 'client_email',
'client_tva' => 'client_tva',
'client_dom' => 'client_dom',
'delivery_name' => 'delivery_name',
'delivery_contact' => 'delivery_contact',
'delivery_address' => 'delivery_address',
'delivery_address_end' => 'delivery_address_end',
'delivery_zip_code' => 'delivery_zip_code',
'delivery_city' => 'delivery_city',
'delivery_country' => 'delivery_country',
'delivery_phone' => 'delivery_phone',
'delivery_fax' => 'delivery_fax',
'delivery_email' => 'delivery_email',
'display_rules' => 'display_rules',
'style' => 'style',
'has_reduction' => 'hasReduction',
'signature' => 'signature',
'external_file' => 'external_file',
'pdf_link' => 'pdf_link',
'external_url' => 'external_url',
'payment_state' => 'payment_state',
'payments' => 'payments',
'total_nettopay' => 'total_nettopay',
'fromquote' => 'fromquote',
'credit' => 'credit',
'acompte' => 'acompte',
'document_model' => 'documentModel',
'created_at' => 'createdAt',
'updated_at' => 'updatedAt'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'title' => 'setTitle',
'name' => 'setName',
'number' => 'setNumber',
'date' => 'setDate',
'company' => 'setCompany',
'category' => 'setCategory',
'user' => 'setUser',
'currency' => 'setCurrency',
'payment_methods' => 'setPaymentMethods',
'shipping' => 'setShipping',
'invoice_lines' => 'setInvoiceLines',
'display_expeditor' => 'setDisplayExpeditor',
'num_tva' => 'setNumTva',
'client_code' => 'setClientCode',
'analytical_code' => 'setAnalyticalCode',
'currency_rate' => 'setCurrencyRate',
'payment_expiry_date' => 'setPaymentExpiryDate',
'payment_date' => 'setPaymentDate',
'payment_method_name' => 'setPaymentMethodName',
'late_penalty_rate' => 'setLatePenaltyRate',
'shipping_total_ht' => 'setShippingTotalHt',
'shipping_tva_rate' => 'setShippingTvaRate',
'shipping_total_tva' => 'setShippingTotalTva',
'shipping_method' => 'setShippingMethod',
'discount_total_ht' => 'setDiscountTotalHt',
'discount_total_type' => 'setDiscountTotalType',
'total_ht_nodiscount' => 'setTotalHtNodiscount',
'total_ht' => 'setTotalHt',
'total_ttc' => 'setTotalTtc',
'total_tva' => 'setTotalTva',
'vat_rates' => 'setVatRates',
'comment' => 'setComment',
'notes' => 'setNotes',
'state' => 'setState',
'sale_date' => 'setSaleDate',
'company_name' => 'setCompanyName',
'company_contact' => 'setCompanyContact',
'company_siren' => 'setCompanySiren',
'company_nic' => 'setCompanyNic',
'company_share_capital' => 'setCompanyShareCapital',
'company_commercial_court' => 'setCompanyCommercialCourt',
'company_num_rcs' => 'setCompanyNumRcs',
'company_num_trade_directory' => 'setCompanyNumTradeDirectory',
'company_type' => 'setCompanyType',
'company_address' => 'setCompanyAddress',
'company_address_end' => 'setCompanyAddressEnd',
'company_zip_code' => 'setCompanyZipCode',
'company_city' => 'setCompanyCity',
'company_country' => 'setCompanyCountry',
'company_phone' => 'setCompanyPhone',
'company_fax' => 'setCompanyFax',
'company_email' => 'setCompanyEmail',
'company_cgv' => 'setCompanyCgv',
'company_include_cgv' => 'setCompanyIncludeCgv',
'client_name' => 'setClientName',
'client_contact' => 'setClientContact',
'client_address' => 'setClientAddress',
'client_address_end' => 'setClientAddressEnd',
'client_zip_code' => 'setClientZipCode',
'client_city' => 'setClientCity',
'client_country' => 'setClientCountry',
'client_phone' => 'setClientPhone',
'client_fax' => 'setClientFax',
'client_email' => 'setClientEmail',
'client_tva' => 'setClientTva',
'client_dom' => 'setClientDom',
'delivery_name' => 'setDeliveryName',
'delivery_contact' => 'setDeliveryContact',
'delivery_address' => 'setDeliveryAddress',
'delivery_address_end' => 'setDeliveryAddressEnd',
'delivery_zip_code' => 'setDeliveryZipCode',
'delivery_city' => 'setDeliveryCity',
'delivery_country' => 'setDeliveryCountry',
'delivery_phone' => 'setDeliveryPhone',
'delivery_fax' => 'setDeliveryFax',
'delivery_email' => 'setDeliveryEmail',
'display_rules' => 'setDisplayRules',
'style' => 'setStyle',
'has_reduction' => 'setHasReduction',
'signature' => 'setSignature',
'external_file' => 'setExternalFile',
'pdf_link' => 'setPdfLink',
'external_url' => 'setExternalUrl',
'payment_state' => 'setPaymentState',
'payments' => 'setPayments',
'total_nettopay' => 'setTotalNettopay',
'fromquote' => 'setFromquote',
'credit' => 'setCredit',
'acompte' => 'setAcompte',
'document_model' => 'setDocumentModel',
'created_at' => 'setCreatedAt',
'updated_at' => 'setUpdatedAt'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'title' => 'getTitle',
'name' => 'getName',
'number' => 'getNumber',
'date' => 'getDate',
'company' => 'getCompany',
'category' => 'getCategory',
'user' => 'getUser',
'currency' => 'getCurrency',
'payment_methods' => 'getPaymentMethods',
'shipping' => 'getShipping',
'invoice_lines' => 'getInvoiceLines',
'display_expeditor' => 'getDisplayExpeditor',
'num_tva' => 'getNumTva',
'client_code' => 'getClientCode',
'analytical_code' => 'getAnalyticalCode',
'currency_rate' => 'getCurrencyRate',
'payment_expiry_date' => 'getPaymentExpiryDate',
'payment_date' => 'getPaymentDate',
'payment_method_name' => 'getPaymentMethodName',
'late_penalty_rate' => 'getLatePenaltyRate',
'shipping_total_ht' => 'getShippingTotalHt',
'shipping_tva_rate' => 'getShippingTvaRate',
'shipping_total_tva' => 'getShippingTotalTva',
'shipping_method' => 'getShippingMethod',
'discount_total_ht' => 'getDiscountTotalHt',
'discount_total_type' => 'getDiscountTotalType',
'total_ht_nodiscount' => 'getTotalHtNodiscount',
'total_ht' => 'getTotalHt',
'total_ttc' => 'getTotalTtc',
'total_tva' => 'getTotalTva',
'vat_rates' => 'getVatRates',
'comment' => 'getComment',
'notes' => 'getNotes',
'state' => 'getState',
'sale_date' => 'getSaleDate',
'company_name' => 'getCompanyName',
'company_contact' => 'getCompanyContact',
'company_siren' => 'getCompanySiren',
'company_nic' => 'getCompanyNic',
'company_share_capital' => 'getCompanyShareCapital',
'company_commercial_court' => 'getCompanyCommercialCourt',
'company_num_rcs' => 'getCompanyNumRcs',
'company_num_trade_directory' => 'getCompanyNumTradeDirectory',
'company_type' => 'getCompanyType',
'company_address' => 'getCompanyAddress',
'company_address_end' => 'getCompanyAddressEnd',
'company_zip_code' => 'getCompanyZipCode',
'company_city' => 'getCompanyCity',
'company_country' => 'getCompanyCountry',
'company_phone' => 'getCompanyPhone',
'company_fax' => 'getCompanyFax',
'company_email' => 'getCompanyEmail',
'company_cgv' => 'getCompanyCgv',
'company_include_cgv' => 'getCompanyIncludeCgv',
'client_name' => 'getClientName',
'client_contact' => 'getClientContact',
'client_address' => 'getClientAddress',
'client_address_end' => 'getClientAddressEnd',
'client_zip_code' => 'getClientZipCode',
'client_city' => 'getClientCity',
'client_country' => 'getClientCountry',
'client_phone' => 'getClientPhone',
'client_fax' => 'getClientFax',
'client_email' => 'getClientEmail',
'client_tva' => 'getClientTva',
'client_dom' => 'getClientDom',
'delivery_name' => 'getDeliveryName',
'delivery_contact' => 'getDeliveryContact',
'delivery_address' => 'getDeliveryAddress',
'delivery_address_end' => 'getDeliveryAddressEnd',
'delivery_zip_code' => 'getDeliveryZipCode',
'delivery_city' => 'getDeliveryCity',
'delivery_country' => 'getDeliveryCountry',
'delivery_phone' => 'getDeliveryPhone',
'delivery_fax' => 'getDeliveryFax',
'delivery_email' => 'getDeliveryEmail',
'display_rules' => 'getDisplayRules',
'style' => 'getStyle',
'has_reduction' => 'getHasReduction',
'signature' => 'getSignature',
'external_file' => 'getExternalFile',
'pdf_link' => 'getPdfLink',
'external_url' => 'getExternalUrl',
'payment_state' => 'getPaymentState',
'payments' => 'getPayments',
'total_nettopay' => 'getTotalNettopay',
'fromquote' => 'getFromquote',
'credit' => 'getCredit',
'acompte' => 'getAcompte',
'document_model' => 'getDocumentModel',
'created_at' => 'getCreatedAt',
'updated_at' => 'getUpdatedAt'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STATE_DRAFT = 'draft';
const STATE_WAITING = 'waiting';
const STATE_PAID = 'paid';
const STATE_NOTPAID = 'notpaid';
const STATE_LATE = 'late';
const STATE_INACTIVE = 'inactive';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_DRAFT,
self::STATE_WAITING,
self::STATE_PAID,
self::STATE_NOTPAID,
self::STATE_LATE,
self::STATE_INACTIVE,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['company'] = isset($data['company']) ? $data['company'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['user'] = isset($data['user']) ? $data['user'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['payment_methods'] = isset($data['payment_methods']) ? $data['payment_methods'] : null;
        $this->container['shipping'] = isset($data['shipping']) ? $data['shipping'] : null;
        $this->container['invoice_lines'] = isset($data['invoice_lines']) ? $data['invoice_lines'] : null;
        $this->container['display_expeditor'] = isset($data['display_expeditor']) ? $data['display_expeditor'] : null;
        $this->container['num_tva'] = isset($data['num_tva']) ? $data['num_tva'] : null;
        $this->container['client_code'] = isset($data['client_code']) ? $data['client_code'] : null;
        $this->container['analytical_code'] = isset($data['analytical_code']) ? $data['analytical_code'] : null;
        $this->container['currency_rate'] = isset($data['currency_rate']) ? $data['currency_rate'] : null;
        $this->container['payment_expiry_date'] = isset($data['payment_expiry_date']) ? $data['payment_expiry_date'] : null;
        $this->container['payment_date'] = isset($data['payment_date']) ? $data['payment_date'] : null;
        $this->container['payment_method_name'] = isset($data['payment_method_name']) ? $data['payment_method_name'] : null;
        $this->container['late_penalty_rate'] = isset($data['late_penalty_rate']) ? $data['late_penalty_rate'] : null;
        $this->container['shipping_total_ht'] = isset($data['shipping_total_ht']) ? $data['shipping_total_ht'] : null;
        $this->container['shipping_tva_rate'] = isset($data['shipping_tva_rate']) ? $data['shipping_tva_rate'] : null;
        $this->container['shipping_total_tva'] = isset($data['shipping_total_tva']) ? $data['shipping_total_tva'] : null;
        $this->container['shipping_method'] = isset($data['shipping_method']) ? $data['shipping_method'] : null;
        $this->container['discount_total_ht'] = isset($data['discount_total_ht']) ? $data['discount_total_ht'] : null;
        $this->container['discount_total_type'] = isset($data['discount_total_type']) ? $data['discount_total_type'] : null;
        $this->container['total_ht_nodiscount'] = isset($data['total_ht_nodiscount']) ? $data['total_ht_nodiscount'] : null;
        $this->container['total_ht'] = isset($data['total_ht']) ? $data['total_ht'] : null;
        $this->container['total_ttc'] = isset($data['total_ttc']) ? $data['total_ttc'] : null;
        $this->container['total_tva'] = isset($data['total_tva']) ? $data['total_tva'] : null;
        $this->container['vat_rates'] = isset($data['vat_rates']) ? $data['vat_rates'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['sale_date'] = isset($data['sale_date']) ? $data['sale_date'] : null;
        $this->container['company_name'] = isset($data['company_name']) ? $data['company_name'] : null;
        $this->container['company_contact'] = isset($data['company_contact']) ? $data['company_contact'] : null;
        $this->container['company_siren'] = isset($data['company_siren']) ? $data['company_siren'] : null;
        $this->container['company_nic'] = isset($data['company_nic']) ? $data['company_nic'] : null;
        $this->container['company_share_capital'] = isset($data['company_share_capital']) ? $data['company_share_capital'] : null;
        $this->container['company_commercial_court'] = isset($data['company_commercial_court']) ? $data['company_commercial_court'] : null;
        $this->container['company_num_rcs'] = isset($data['company_num_rcs']) ? $data['company_num_rcs'] : null;
        $this->container['company_num_trade_directory'] = isset($data['company_num_trade_directory']) ? $data['company_num_trade_directory'] : null;
        $this->container['company_type'] = isset($data['company_type']) ? $data['company_type'] : null;
        $this->container['company_address'] = isset($data['company_address']) ? $data['company_address'] : null;
        $this->container['company_address_end'] = isset($data['company_address_end']) ? $data['company_address_end'] : null;
        $this->container['company_zip_code'] = isset($data['company_zip_code']) ? $data['company_zip_code'] : null;
        $this->container['company_city'] = isset($data['company_city']) ? $data['company_city'] : null;
        $this->container['company_country'] = isset($data['company_country']) ? $data['company_country'] : null;
        $this->container['company_phone'] = isset($data['company_phone']) ? $data['company_phone'] : null;
        $this->container['company_fax'] = isset($data['company_fax']) ? $data['company_fax'] : null;
        $this->container['company_email'] = isset($data['company_email']) ? $data['company_email'] : null;
        $this->container['company_cgv'] = isset($data['company_cgv']) ? $data['company_cgv'] : null;
        $this->container['company_include_cgv'] = isset($data['company_include_cgv']) ? $data['company_include_cgv'] : null;
        $this->container['client_name'] = isset($data['client_name']) ? $data['client_name'] : null;
        $this->container['client_contact'] = isset($data['client_contact']) ? $data['client_contact'] : null;
        $this->container['client_address'] = isset($data['client_address']) ? $data['client_address'] : null;
        $this->container['client_address_end'] = isset($data['client_address_end']) ? $data['client_address_end'] : null;
        $this->container['client_zip_code'] = isset($data['client_zip_code']) ? $data['client_zip_code'] : null;
        $this->container['client_city'] = isset($data['client_city']) ? $data['client_city'] : null;
        $this->container['client_country'] = isset($data['client_country']) ? $data['client_country'] : null;
        $this->container['client_phone'] = isset($data['client_phone']) ? $data['client_phone'] : null;
        $this->container['client_fax'] = isset($data['client_fax']) ? $data['client_fax'] : null;
        $this->container['client_email'] = isset($data['client_email']) ? $data['client_email'] : null;
        $this->container['client_tva'] = isset($data['client_tva']) ? $data['client_tva'] : null;
        $this->container['client_dom'] = isset($data['client_dom']) ? $data['client_dom'] : null;
        $this->container['delivery_name'] = isset($data['delivery_name']) ? $data['delivery_name'] : null;
        $this->container['delivery_contact'] = isset($data['delivery_contact']) ? $data['delivery_contact'] : null;
        $this->container['delivery_address'] = isset($data['delivery_address']) ? $data['delivery_address'] : null;
        $this->container['delivery_address_end'] = isset($data['delivery_address_end']) ? $data['delivery_address_end'] : null;
        $this->container['delivery_zip_code'] = isset($data['delivery_zip_code']) ? $data['delivery_zip_code'] : null;
        $this->container['delivery_city'] = isset($data['delivery_city']) ? $data['delivery_city'] : null;
        $this->container['delivery_country'] = isset($data['delivery_country']) ? $data['delivery_country'] : null;
        $this->container['delivery_phone'] = isset($data['delivery_phone']) ? $data['delivery_phone'] : null;
        $this->container['delivery_fax'] = isset($data['delivery_fax']) ? $data['delivery_fax'] : null;
        $this->container['delivery_email'] = isset($data['delivery_email']) ? $data['delivery_email'] : null;
        $this->container['display_rules'] = isset($data['display_rules']) ? $data['display_rules'] : null;
        $this->container['style'] = isset($data['style']) ? $data['style'] : null;
        $this->container['has_reduction'] = isset($data['has_reduction']) ? $data['has_reduction'] : null;
        $this->container['signature'] = isset($data['signature']) ? $data['signature'] : null;
        $this->container['external_file'] = isset($data['external_file']) ? $data['external_file'] : null;
        $this->container['pdf_link'] = isset($data['pdf_link']) ? $data['pdf_link'] : null;
        $this->container['external_url'] = isset($data['external_url']) ? $data['external_url'] : null;
        $this->container['payment_state'] = isset($data['payment_state']) ? $data['payment_state'] : null;
        $this->container['payments'] = isset($data['payments']) ? $data['payments'] : null;
        $this->container['total_nettopay'] = isset($data['total_nettopay']) ? $data['total_nettopay'] : null;
        $this->container['fromquote'] = isset($data['fromquote']) ? $data['fromquote'] : null;
        $this->container['credit'] = isset($data['credit']) ? $data['credit'] : null;
        $this->container['acompte'] = isset($data['acompte']) ? $data['acompte'] : null;
        $this->container['document_model'] = isset($data['document_model']) ? $data['document_model'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['invoice_lines'] === null) {
            $invalidProperties[] = "'invoice_lines' can't be null";
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['client_name'] === null) {
            $invalidProperties[] = "'client_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets date
     *
     * @return object
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param object $date date
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets company
     *
     * @return object
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param object $company company
     *
     * @return $this
     */
    public function setCompany($company)
    {
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets category
     *
     * @return object
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param object $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets user
     *
     * @return object
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param object $user user
     *
     * @return $this
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return object
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param object $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets payment_methods
     *
     * @return object
     */
    public function getPaymentMethods()
    {
        return $this->container['payment_methods'];
    }

    /**
     * Sets payment_methods
     *
     * @param object $payment_methods payment_methods
     *
     * @return $this
     */
    public function setPaymentMethods($payment_methods)
    {
        $this->container['payment_methods'] = $payment_methods;

        return $this;
    }

    /**
     * Gets shipping
     *
     * @return object
     */
    public function getShipping()
    {
        return $this->container['shipping'];
    }

    /**
     * Sets shipping
     *
     * @param object $shipping shipping
     *
     * @return $this
     */
    public function setShipping($shipping)
    {
        $this->container['shipping'] = $shipping;

        return $this;
    }

    /**
     * Gets invoice_lines
     *
     * @return \Wuro\Api\Model\InvoiceLine[]
     */
    public function getInvoiceLines()
    {
        return $this->container['invoice_lines'];
    }

    /**
     * Sets invoice_lines
     *
     * @param \Wuro\Api\Model\InvoiceLine[] $invoice_lines invoice_lines
     *
     * @return $this
     */
    public function setInvoiceLines($invoice_lines)
    {
        $this->container['invoice_lines'] = $invoice_lines;

        return $this;
    }

    /**
     * Gets display_expeditor
     *
     * @return bool
     */
    public function getDisplayExpeditor()
    {
        return $this->container['display_expeditor'];
    }

    /**
     * Sets display_expeditor
     *
     * @param bool $display_expeditor display_expeditor
     *
     * @return $this
     */
    public function setDisplayExpeditor($display_expeditor)
    {
        $this->container['display_expeditor'] = $display_expeditor;

        return $this;
    }

    /**
     * Gets num_tva
     *
     * @return string
     */
    public function getNumTva()
    {
        return $this->container['num_tva'];
    }

    /**
     * Sets num_tva
     *
     * @param string $num_tva num_tva
     *
     * @return $this
     */
    public function setNumTva($num_tva)
    {
        $this->container['num_tva'] = $num_tva;

        return $this;
    }

    /**
     * Gets client_code
     *
     * @return string
     */
    public function getClientCode()
    {
        return $this->container['client_code'];
    }

    /**
     * Sets client_code
     *
     * @param string $client_code client_code
     *
     * @return $this
     */
    public function setClientCode($client_code)
    {
        $this->container['client_code'] = $client_code;

        return $this;
    }

    /**
     * Gets analytical_code
     *
     * @return string
     */
    public function getAnalyticalCode()
    {
        return $this->container['analytical_code'];
    }

    /**
     * Sets analytical_code
     *
     * @param string $analytical_code analytical_code
     *
     * @return $this
     */
    public function setAnalyticalCode($analytical_code)
    {
        $this->container['analytical_code'] = $analytical_code;

        return $this;
    }

    /**
     * Gets currency_rate
     *
     * @return string
     */
    public function getCurrencyRate()
    {
        return $this->container['currency_rate'];
    }

    /**
     * Sets currency_rate
     *
     * @param string $currency_rate currency_rate
     *
     * @return $this
     */
    public function setCurrencyRate($currency_rate)
    {
        $this->container['currency_rate'] = $currency_rate;

        return $this;
    }

    /**
     * Gets payment_expiry_date
     *
     * @return string
     */
    public function getPaymentExpiryDate()
    {
        return $this->container['payment_expiry_date'];
    }

    /**
     * Sets payment_expiry_date
     *
     * @param string $payment_expiry_date payment_expiry_date
     *
     * @return $this
     */
    public function setPaymentExpiryDate($payment_expiry_date)
    {
        $this->container['payment_expiry_date'] = $payment_expiry_date;

        return $this;
    }

    /**
     * Gets payment_date
     *
     * @return string
     */
    public function getPaymentDate()
    {
        return $this->container['payment_date'];
    }

    /**
     * Sets payment_date
     *
     * @param string $payment_date payment_date
     *
     * @return $this
     */
    public function setPaymentDate($payment_date)
    {
        $this->container['payment_date'] = $payment_date;

        return $this;
    }

    /**
     * Gets payment_method_name
     *
     * @return string
     */
    public function getPaymentMethodName()
    {
        return $this->container['payment_method_name'];
    }

    /**
     * Sets payment_method_name
     *
     * @param string $payment_method_name payment_method_name
     *
     * @return $this
     */
    public function setPaymentMethodName($payment_method_name)
    {
        $this->container['payment_method_name'] = $payment_method_name;

        return $this;
    }

    /**
     * Gets late_penalty_rate
     *
     * @return float
     */
    public function getLatePenaltyRate()
    {
        return $this->container['late_penalty_rate'];
    }

    /**
     * Sets late_penalty_rate
     *
     * @param float $late_penalty_rate late_penalty_rate
     *
     * @return $this
     */
    public function setLatePenaltyRate($late_penalty_rate)
    {
        $this->container['late_penalty_rate'] = $late_penalty_rate;

        return $this;
    }

    /**
     * Gets shipping_total_ht
     *
     * @return string
     */
    public function getShippingTotalHt()
    {
        return $this->container['shipping_total_ht'];
    }

    /**
     * Sets shipping_total_ht
     *
     * @param string $shipping_total_ht shipping_total_ht
     *
     * @return $this
     */
    public function setShippingTotalHt($shipping_total_ht)
    {
        $this->container['shipping_total_ht'] = $shipping_total_ht;

        return $this;
    }

    /**
     * Gets shipping_tva_rate
     *
     * @return string
     */
    public function getShippingTvaRate()
    {
        return $this->container['shipping_tva_rate'];
    }

    /**
     * Sets shipping_tva_rate
     *
     * @param string $shipping_tva_rate shipping_tva_rate
     *
     * @return $this
     */
    public function setShippingTvaRate($shipping_tva_rate)
    {
        $this->container['shipping_tva_rate'] = $shipping_tva_rate;

        return $this;
    }

    /**
     * Gets shipping_total_tva
     *
     * @return float
     */
    public function getShippingTotalTva()
    {
        return $this->container['shipping_total_tva'];
    }

    /**
     * Sets shipping_total_tva
     *
     * @param float $shipping_total_tva shipping_total_tva
     *
     * @return $this
     */
    public function setShippingTotalTva($shipping_total_tva)
    {
        $this->container['shipping_total_tva'] = $shipping_total_tva;

        return $this;
    }

    /**
     * Gets shipping_method
     *
     * @return string
     */
    public function getShippingMethod()
    {
        return $this->container['shipping_method'];
    }

    /**
     * Sets shipping_method
     *
     * @param string $shipping_method shipping_method
     *
     * @return $this
     */
    public function setShippingMethod($shipping_method)
    {
        $this->container['shipping_method'] = $shipping_method;

        return $this;
    }

    /**
     * Gets discount_total_ht
     *
     * @return string
     */
    public function getDiscountTotalHt()
    {
        return $this->container['discount_total_ht'];
    }

    /**
     * Sets discount_total_ht
     *
     * @param string $discount_total_ht discount_total_ht
     *
     * @return $this
     */
    public function setDiscountTotalHt($discount_total_ht)
    {
        $this->container['discount_total_ht'] = $discount_total_ht;

        return $this;
    }

    /**
     * Gets discount_total_type
     *
     * @return string
     */
    public function getDiscountTotalType()
    {
        return $this->container['discount_total_type'];
    }

    /**
     * Sets discount_total_type
     *
     * @param string $discount_total_type discount_total_type
     *
     * @return $this
     */
    public function setDiscountTotalType($discount_total_type)
    {
        $this->container['discount_total_type'] = $discount_total_type;

        return $this;
    }

    /**
     * Gets total_ht_nodiscount
     *
     * @return float
     */
    public function getTotalHtNodiscount()
    {
        return $this->container['total_ht_nodiscount'];
    }

    /**
     * Sets total_ht_nodiscount
     *
     * @param float $total_ht_nodiscount total_ht_nodiscount
     *
     * @return $this
     */
    public function setTotalHtNodiscount($total_ht_nodiscount)
    {
        $this->container['total_ht_nodiscount'] = $total_ht_nodiscount;

        return $this;
    }

    /**
     * Gets total_ht
     *
     * @return float
     */
    public function getTotalHt()
    {
        return $this->container['total_ht'];
    }

    /**
     * Sets total_ht
     *
     * @param float $total_ht total_ht
     *
     * @return $this
     */
    public function setTotalHt($total_ht)
    {
        $this->container['total_ht'] = $total_ht;

        return $this;
    }

    /**
     * Gets total_ttc
     *
     * @return float
     */
    public function getTotalTtc()
    {
        return $this->container['total_ttc'];
    }

    /**
     * Sets total_ttc
     *
     * @param float $total_ttc total_ttc
     *
     * @return $this
     */
    public function setTotalTtc($total_ttc)
    {
        $this->container['total_ttc'] = $total_ttc;

        return $this;
    }

    /**
     * Gets total_tva
     *
     * @return float
     */
    public function getTotalTva()
    {
        return $this->container['total_tva'];
    }

    /**
     * Sets total_tva
     *
     * @param float $total_tva total_tva
     *
     * @return $this
     */
    public function setTotalTva($total_tva)
    {
        $this->container['total_tva'] = $total_tva;

        return $this;
    }

    /**
     * Gets vat_rates
     *
     * @return object[]
     */
    public function getVatRates()
    {
        return $this->container['vat_rates'];
    }

    /**
     * Sets vat_rates
     *
     * @param object[] $vat_rates vat_rates
     *
     * @return $this
     */
    public function setVatRates($vat_rates)
    {
        $this->container['vat_rates'] = $vat_rates;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment comment
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string $notes notes
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($state) && !in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets sale_date
     *
     * @return string
     */
    public function getSaleDate()
    {
        return $this->container['sale_date'];
    }

    /**
     * Sets sale_date
     *
     * @param string $sale_date sale_date
     *
     * @return $this
     */
    public function setSaleDate($sale_date)
    {
        $this->container['sale_date'] = $sale_date;

        return $this;
    }

    /**
     * Gets company_name
     *
     * @return string
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     *
     * @param string $company_name company_name
     *
     * @return $this
     */
    public function setCompanyName($company_name)
    {
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets company_contact
     *
     * @return string
     */
    public function getCompanyContact()
    {
        return $this->container['company_contact'];
    }

    /**
     * Sets company_contact
     *
     * @param string $company_contact company_contact
     *
     * @return $this
     */
    public function setCompanyContact($company_contact)
    {
        $this->container['company_contact'] = $company_contact;

        return $this;
    }

    /**
     * Gets company_siren
     *
     * @return string
     */
    public function getCompanySiren()
    {
        return $this->container['company_siren'];
    }

    /**
     * Sets company_siren
     *
     * @param string $company_siren company_siren
     *
     * @return $this
     */
    public function setCompanySiren($company_siren)
    {
        $this->container['company_siren'] = $company_siren;

        return $this;
    }

    /**
     * Gets company_nic
     *
     * @return string
     */
    public function getCompanyNic()
    {
        return $this->container['company_nic'];
    }

    /**
     * Sets company_nic
     *
     * @param string $company_nic company_nic
     *
     * @return $this
     */
    public function setCompanyNic($company_nic)
    {
        $this->container['company_nic'] = $company_nic;

        return $this;
    }

    /**
     * Gets company_share_capital
     *
     * @return float
     */
    public function getCompanyShareCapital()
    {
        return $this->container['company_share_capital'];
    }

    /**
     * Sets company_share_capital
     *
     * @param float $company_share_capital company_share_capital
     *
     * @return $this
     */
    public function setCompanyShareCapital($company_share_capital)
    {
        $this->container['company_share_capital'] = $company_share_capital;

        return $this;
    }

    /**
     * Gets company_commercial_court
     *
     * @return string
     */
    public function getCompanyCommercialCourt()
    {
        return $this->container['company_commercial_court'];
    }

    /**
     * Sets company_commercial_court
     *
     * @param string $company_commercial_court company_commercial_court
     *
     * @return $this
     */
    public function setCompanyCommercialCourt($company_commercial_court)
    {
        $this->container['company_commercial_court'] = $company_commercial_court;

        return $this;
    }

    /**
     * Gets company_num_rcs
     *
     * @return string
     */
    public function getCompanyNumRcs()
    {
        return $this->container['company_num_rcs'];
    }

    /**
     * Sets company_num_rcs
     *
     * @param string $company_num_rcs company_num_rcs
     *
     * @return $this
     */
    public function setCompanyNumRcs($company_num_rcs)
    {
        $this->container['company_num_rcs'] = $company_num_rcs;

        return $this;
    }

    /**
     * Gets company_num_trade_directory
     *
     * @return string
     */
    public function getCompanyNumTradeDirectory()
    {
        return $this->container['company_num_trade_directory'];
    }

    /**
     * Sets company_num_trade_directory
     *
     * @param string $company_num_trade_directory company_num_trade_directory
     *
     * @return $this
     */
    public function setCompanyNumTradeDirectory($company_num_trade_directory)
    {
        $this->container['company_num_trade_directory'] = $company_num_trade_directory;

        return $this;
    }

    /**
     * Gets company_type
     *
     * @return string
     */
    public function getCompanyType()
    {
        return $this->container['company_type'];
    }

    /**
     * Sets company_type
     *
     * @param string $company_type company_type
     *
     * @return $this
     */
    public function setCompanyType($company_type)
    {
        $this->container['company_type'] = $company_type;

        return $this;
    }

    /**
     * Gets company_address
     *
     * @return string
     */
    public function getCompanyAddress()
    {
        return $this->container['company_address'];
    }

    /**
     * Sets company_address
     *
     * @param string $company_address company_address
     *
     * @return $this
     */
    public function setCompanyAddress($company_address)
    {
        $this->container['company_address'] = $company_address;

        return $this;
    }

    /**
     * Gets company_address_end
     *
     * @return string
     */
    public function getCompanyAddressEnd()
    {
        return $this->container['company_address_end'];
    }

    /**
     * Sets company_address_end
     *
     * @param string $company_address_end company_address_end
     *
     * @return $this
     */
    public function setCompanyAddressEnd($company_address_end)
    {
        $this->container['company_address_end'] = $company_address_end;

        return $this;
    }

    /**
     * Gets company_zip_code
     *
     * @return string
     */
    public function getCompanyZipCode()
    {
        return $this->container['company_zip_code'];
    }

    /**
     * Sets company_zip_code
     *
     * @param string $company_zip_code company_zip_code
     *
     * @return $this
     */
    public function setCompanyZipCode($company_zip_code)
    {
        $this->container['company_zip_code'] = $company_zip_code;

        return $this;
    }

    /**
     * Gets company_city
     *
     * @return string
     */
    public function getCompanyCity()
    {
        return $this->container['company_city'];
    }

    /**
     * Sets company_city
     *
     * @param string $company_city company_city
     *
     * @return $this
     */
    public function setCompanyCity($company_city)
    {
        $this->container['company_city'] = $company_city;

        return $this;
    }

    /**
     * Gets company_country
     *
     * @return string
     */
    public function getCompanyCountry()
    {
        return $this->container['company_country'];
    }

    /**
     * Sets company_country
     *
     * @param string $company_country company_country
     *
     * @return $this
     */
    public function setCompanyCountry($company_country)
    {
        $this->container['company_country'] = $company_country;

        return $this;
    }

    /**
     * Gets company_phone
     *
     * @return string
     */
    public function getCompanyPhone()
    {
        return $this->container['company_phone'];
    }

    /**
     * Sets company_phone
     *
     * @param string $company_phone company_phone
     *
     * @return $this
     */
    public function setCompanyPhone($company_phone)
    {
        $this->container['company_phone'] = $company_phone;

        return $this;
    }

    /**
     * Gets company_fax
     *
     * @return string
     */
    public function getCompanyFax()
    {
        return $this->container['company_fax'];
    }

    /**
     * Sets company_fax
     *
     * @param string $company_fax company_fax
     *
     * @return $this
     */
    public function setCompanyFax($company_fax)
    {
        $this->container['company_fax'] = $company_fax;

        return $this;
    }

    /**
     * Gets company_email
     *
     * @return string
     */
    public function getCompanyEmail()
    {
        return $this->container['company_email'];
    }

    /**
     * Sets company_email
     *
     * @param string $company_email company_email
     *
     * @return $this
     */
    public function setCompanyEmail($company_email)
    {
        $this->container['company_email'] = $company_email;

        return $this;
    }

    /**
     * Gets company_cgv
     *
     * @return string
     */
    public function getCompanyCgv()
    {
        return $this->container['company_cgv'];
    }

    /**
     * Sets company_cgv
     *
     * @param string $company_cgv company_cgv
     *
     * @return $this
     */
    public function setCompanyCgv($company_cgv)
    {
        $this->container['company_cgv'] = $company_cgv;

        return $this;
    }

    /**
     * Gets company_include_cgv
     *
     * @return bool
     */
    public function getCompanyIncludeCgv()
    {
        return $this->container['company_include_cgv'];
    }

    /**
     * Sets company_include_cgv
     *
     * @param bool $company_include_cgv company_include_cgv
     *
     * @return $this
     */
    public function setCompanyIncludeCgv($company_include_cgv)
    {
        $this->container['company_include_cgv'] = $company_include_cgv;

        return $this;
    }

    /**
     * Gets client_name
     *
     * @return string
     */
    public function getClientName()
    {
        return $this->container['client_name'];
    }

    /**
     * Sets client_name
     *
     * @param string $client_name client_name
     *
     * @return $this
     */
    public function setClientName($client_name)
    {
        $this->container['client_name'] = $client_name;

        return $this;
    }

    /**
     * Gets client_contact
     *
     * @return string
     */
    public function getClientContact()
    {
        return $this->container['client_contact'];
    }

    /**
     * Sets client_contact
     *
     * @param string $client_contact client_contact
     *
     * @return $this
     */
    public function setClientContact($client_contact)
    {
        $this->container['client_contact'] = $client_contact;

        return $this;
    }

    /**
     * Gets client_address
     *
     * @return string
     */
    public function getClientAddress()
    {
        return $this->container['client_address'];
    }

    /**
     * Sets client_address
     *
     * @param string $client_address client_address
     *
     * @return $this
     */
    public function setClientAddress($client_address)
    {
        $this->container['client_address'] = $client_address;

        return $this;
    }

    /**
     * Gets client_address_end
     *
     * @return string
     */
    public function getClientAddressEnd()
    {
        return $this->container['client_address_end'];
    }

    /**
     * Sets client_address_end
     *
     * @param string $client_address_end client_address_end
     *
     * @return $this
     */
    public function setClientAddressEnd($client_address_end)
    {
        $this->container['client_address_end'] = $client_address_end;

        return $this;
    }

    /**
     * Gets client_zip_code
     *
     * @return string
     */
    public function getClientZipCode()
    {
        return $this->container['client_zip_code'];
    }

    /**
     * Sets client_zip_code
     *
     * @param string $client_zip_code client_zip_code
     *
     * @return $this
     */
    public function setClientZipCode($client_zip_code)
    {
        $this->container['client_zip_code'] = $client_zip_code;

        return $this;
    }

    /**
     * Gets client_city
     *
     * @return string
     */
    public function getClientCity()
    {
        return $this->container['client_city'];
    }

    /**
     * Sets client_city
     *
     * @param string $client_city client_city
     *
     * @return $this
     */
    public function setClientCity($client_city)
    {
        $this->container['client_city'] = $client_city;

        return $this;
    }

    /**
     * Gets client_country
     *
     * @return string
     */
    public function getClientCountry()
    {
        return $this->container['client_country'];
    }

    /**
     * Sets client_country
     *
     * @param string $client_country client_country
     *
     * @return $this
     */
    public function setClientCountry($client_country)
    {
        $this->container['client_country'] = $client_country;

        return $this;
    }

    /**
     * Gets client_phone
     *
     * @return string
     */
    public function getClientPhone()
    {
        return $this->container['client_phone'];
    }

    /**
     * Sets client_phone
     *
     * @param string $client_phone client_phone
     *
     * @return $this
     */
    public function setClientPhone($client_phone)
    {
        $this->container['client_phone'] = $client_phone;

        return $this;
    }

    /**
     * Gets client_fax
     *
     * @return string
     */
    public function getClientFax()
    {
        return $this->container['client_fax'];
    }

    /**
     * Sets client_fax
     *
     * @param string $client_fax client_fax
     *
     * @return $this
     */
    public function setClientFax($client_fax)
    {
        $this->container['client_fax'] = $client_fax;

        return $this;
    }

    /**
     * Gets client_email
     *
     * @return string
     */
    public function getClientEmail()
    {
        return $this->container['client_email'];
    }

    /**
     * Sets client_email
     *
     * @param string $client_email client_email
     *
     * @return $this
     */
    public function setClientEmail($client_email)
    {
        $this->container['client_email'] = $client_email;

        return $this;
    }

    /**
     * Gets client_tva
     *
     * @return string
     */
    public function getClientTva()
    {
        return $this->container['client_tva'];
    }

    /**
     * Sets client_tva
     *
     * @param string $client_tva client_tva
     *
     * @return $this
     */
    public function setClientTva($client_tva)
    {
        $this->container['client_tva'] = $client_tva;

        return $this;
    }

    /**
     * Gets client_dom
     *
     * @return bool
     */
    public function getClientDom()
    {
        return $this->container['client_dom'];
    }

    /**
     * Sets client_dom
     *
     * @param bool $client_dom client_dom
     *
     * @return $this
     */
    public function setClientDom($client_dom)
    {
        $this->container['client_dom'] = $client_dom;

        return $this;
    }

    /**
     * Gets delivery_name
     *
     * @return string
     */
    public function getDeliveryName()
    {
        return $this->container['delivery_name'];
    }

    /**
     * Sets delivery_name
     *
     * @param string $delivery_name delivery_name
     *
     * @return $this
     */
    public function setDeliveryName($delivery_name)
    {
        $this->container['delivery_name'] = $delivery_name;

        return $this;
    }

    /**
     * Gets delivery_contact
     *
     * @return string
     */
    public function getDeliveryContact()
    {
        return $this->container['delivery_contact'];
    }

    /**
     * Sets delivery_contact
     *
     * @param string $delivery_contact delivery_contact
     *
     * @return $this
     */
    public function setDeliveryContact($delivery_contact)
    {
        $this->container['delivery_contact'] = $delivery_contact;

        return $this;
    }

    /**
     * Gets delivery_address
     *
     * @return string
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }

    /**
     * Sets delivery_address
     *
     * @param string $delivery_address delivery_address
     *
     * @return $this
     */
    public function setDeliveryAddress($delivery_address)
    {
        $this->container['delivery_address'] = $delivery_address;

        return $this;
    }

    /**
     * Gets delivery_address_end
     *
     * @return string
     */
    public function getDeliveryAddressEnd()
    {
        return $this->container['delivery_address_end'];
    }

    /**
     * Sets delivery_address_end
     *
     * @param string $delivery_address_end delivery_address_end
     *
     * @return $this
     */
    public function setDeliveryAddressEnd($delivery_address_end)
    {
        $this->container['delivery_address_end'] = $delivery_address_end;

        return $this;
    }

    /**
     * Gets delivery_zip_code
     *
     * @return string
     */
    public function getDeliveryZipCode()
    {
        return $this->container['delivery_zip_code'];
    }

    /**
     * Sets delivery_zip_code
     *
     * @param string $delivery_zip_code delivery_zip_code
     *
     * @return $this
     */
    public function setDeliveryZipCode($delivery_zip_code)
    {
        $this->container['delivery_zip_code'] = $delivery_zip_code;

        return $this;
    }

    /**
     * Gets delivery_city
     *
     * @return string
     */
    public function getDeliveryCity()
    {
        return $this->container['delivery_city'];
    }

    /**
     * Sets delivery_city
     *
     * @param string $delivery_city delivery_city
     *
     * @return $this
     */
    public function setDeliveryCity($delivery_city)
    {
        $this->container['delivery_city'] = $delivery_city;

        return $this;
    }

    /**
     * Gets delivery_country
     *
     * @return string
     */
    public function getDeliveryCountry()
    {
        return $this->container['delivery_country'];
    }

    /**
     * Sets delivery_country
     *
     * @param string $delivery_country delivery_country
     *
     * @return $this
     */
    public function setDeliveryCountry($delivery_country)
    {
        $this->container['delivery_country'] = $delivery_country;

        return $this;
    }

    /**
     * Gets delivery_phone
     *
     * @return string
     */
    public function getDeliveryPhone()
    {
        return $this->container['delivery_phone'];
    }

    /**
     * Sets delivery_phone
     *
     * @param string $delivery_phone delivery_phone
     *
     * @return $this
     */
    public function setDeliveryPhone($delivery_phone)
    {
        $this->container['delivery_phone'] = $delivery_phone;

        return $this;
    }

    /**
     * Gets delivery_fax
     *
     * @return string
     */
    public function getDeliveryFax()
    {
        return $this->container['delivery_fax'];
    }

    /**
     * Sets delivery_fax
     *
     * @param string $delivery_fax delivery_fax
     *
     * @return $this
     */
    public function setDeliveryFax($delivery_fax)
    {
        $this->container['delivery_fax'] = $delivery_fax;

        return $this;
    }

    /**
     * Gets delivery_email
     *
     * @return string
     */
    public function getDeliveryEmail()
    {
        return $this->container['delivery_email'];
    }

    /**
     * Sets delivery_email
     *
     * @param string $delivery_email delivery_email
     *
     * @return $this
     */
    public function setDeliveryEmail($delivery_email)
    {
        $this->container['delivery_email'] = $delivery_email;

        return $this;
    }

    /**
     * Gets display_rules
     *
     * @return object
     */
    public function getDisplayRules()
    {
        return $this->container['display_rules'];
    }

    /**
     * Sets display_rules
     *
     * @param object $display_rules display_rules
     *
     * @return $this
     */
    public function setDisplayRules($display_rules)
    {
        $this->container['display_rules'] = $display_rules;

        return $this;
    }

    /**
     * Gets style
     *
     * @return object
     */
    public function getStyle()
    {
        return $this->container['style'];
    }

    /**
     * Sets style
     *
     * @param object $style style
     *
     * @return $this
     */
    public function setStyle($style)
    {
        $this->container['style'] = $style;

        return $this;
    }

    /**
     * Gets has_reduction
     *
     * @return bool
     */
    public function getHasReduction()
    {
        return $this->container['has_reduction'];
    }

    /**
     * Sets has_reduction
     *
     * @param bool $has_reduction has_reduction
     *
     * @return $this
     */
    public function setHasReduction($has_reduction)
    {
        $this->container['has_reduction'] = $has_reduction;

        return $this;
    }

    /**
     * Gets signature
     *
     * @return object
     */
    public function getSignature()
    {
        return $this->container['signature'];
    }

    /**
     * Sets signature
     *
     * @param object $signature signature
     *
     * @return $this
     */
    public function setSignature($signature)
    {
        $this->container['signature'] = $signature;

        return $this;
    }

    /**
     * Gets external_file
     *
     * @return string
     */
    public function getExternalFile()
    {
        return $this->container['external_file'];
    }

    /**
     * Sets external_file
     *
     * @param string $external_file external_file
     *
     * @return $this
     */
    public function setExternalFile($external_file)
    {
        $this->container['external_file'] = $external_file;

        return $this;
    }

    /**
     * Gets pdf_link
     *
     * @return string
     */
    public function getPdfLink()
    {
        return $this->container['pdf_link'];
    }

    /**
     * Sets pdf_link
     *
     * @param string $pdf_link pdf_link
     *
     * @return $this
     */
    public function setPdfLink($pdf_link)
    {
        $this->container['pdf_link'] = $pdf_link;

        return $this;
    }

    /**
     * Gets external_url
     *
     * @return string
     */
    public function getExternalUrl()
    {
        return $this->container['external_url'];
    }

    /**
     * Sets external_url
     *
     * @param string $external_url external_url
     *
     * @return $this
     */
    public function setExternalUrl($external_url)
    {
        $this->container['external_url'] = $external_url;

        return $this;
    }

    /**
     * Gets payment_state
     *
     * @return string
     */
    public function getPaymentState()
    {
        return $this->container['payment_state'];
    }

    /**
     * Sets payment_state
     *
     * @param string $payment_state payment_state
     *
     * @return $this
     */
    public function setPaymentState($payment_state)
    {
        $this->container['payment_state'] = $payment_state;

        return $this;
    }

    /**
     * Gets payments
     *
     * @return \Wuro\Api\Model\Payment[][]
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param \Wuro\Api\Model\Payment[][] $payments payments
     *
     * @return $this
     */
    public function setPayments($payments)
    {
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets total_nettopay
     *
     * @return float
     */
    public function getTotalNettopay()
    {
        return $this->container['total_nettopay'];
    }

    /**
     * Sets total_nettopay
     *
     * @param float $total_nettopay total_nettopay
     *
     * @return $this
     */
    public function setTotalNettopay($total_nettopay)
    {
        $this->container['total_nettopay'] = $total_nettopay;

        return $this;
    }

    /**
     * Gets fromquote
     *
     * @return string
     */
    public function getFromquote()
    {
        return $this->container['fromquote'];
    }

    /**
     * Sets fromquote
     *
     * @param string $fromquote fromquote
     *
     * @return $this
     */
    public function setFromquote($fromquote)
    {
        $this->container['fromquote'] = $fromquote;

        return $this;
    }

    /**
     * Gets credit
     *
     * @return bool
     */
    public function getCredit()
    {
        return $this->container['credit'];
    }

    /**
     * Sets credit
     *
     * @param bool $credit credit
     *
     * @return $this
     */
    public function setCredit($credit)
    {
        $this->container['credit'] = $credit;

        return $this;
    }

    /**
     * Gets acompte
     *
     * @return bool
     */
    public function getAcompte()
    {
        return $this->container['acompte'];
    }

    /**
     * Sets acompte
     *
     * @param bool $acompte acompte
     *
     * @return $this
     */
    public function setAcompte($acompte)
    {
        $this->container['acompte'] = $acompte;

        return $this;
    }

    /**
     * Gets document_model
     *
     * @return string
     */
    public function getDocumentModel()
    {
        return $this->container['document_model'];
    }

    /**
     * Sets document_model
     *
     * @param string $document_model document_model
     *
     * @return $this
     */
    public function setDocumentModel($document_model)
    {
        $this->container['document_model'] = $document_model;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
