<?php
/**
 * InvoiceLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wuro\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wuro API
 *
 * API de votre espace Wuro, connectez-vous sur https://wuro.pro, dans les paramètres de votre entreprise \"Développeurs (API)\", créez une application avec un scope défini afin de demander un jeton d'accès (GET accessToken) avec vos identifiants
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.17
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Wuro\Api;

/**
 * InvoiceLineTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceLine
 * @package     Wuro\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceLine"
     */
    public function testInvoiceLine()
    {
    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "price_ht"
     */
    public function testPropertyPriceHt()
    {
    }

    /**
     * Test attribute "price_ttc"
     */
    public function testPropertyPriceTtc()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "total_ht"
     */
    public function testPropertyTotalHt()
    {
    }

    /**
     * Test attribute "tva"
     */
    public function testPropertyTva()
    {
    }

    /**
     * Test attribute "tva_rate"
     */
    public function testPropertyTvaRate()
    {
    }

    /**
     * Test attribute "discount_ht"
     */
    public function testPropertyDiscountHt()
    {
    }

    /**
     * Test attribute "discount_type"
     */
    public function testPropertyDiscountType()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
