<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wuro\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wuro API
 *
 * API de votre espace Wuro, connectez-vous sur https://wuro.pro, dans les paramètres de votre entreprise \"Développeurs (API)\", créez une application avec un scope défini afin de demander un jeton d'accès (GET accessToken) avec vos identifiants
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Wuro\Api;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class
 * @description Invoice
 * @package     Wuro\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "shipping"
     */
    public function testPropertyShipping()
    {
    }

    /**
     * Test attribute "invoice_lines"
     */
    public function testPropertyInvoiceLines()
    {
    }

    /**
     * Test attribute "display_expeditor"
     */
    public function testPropertyDisplayExpeditor()
    {
    }

    /**
     * Test attribute "num_tva"
     */
    public function testPropertyNumTva()
    {
    }

    /**
     * Test attribute "client_code"
     */
    public function testPropertyClientCode()
    {
    }

    /**
     * Test attribute "analytical_code"
     */
    public function testPropertyAnalyticalCode()
    {
    }

    /**
     * Test attribute "currency_rate"
     */
    public function testPropertyCurrencyRate()
    {
    }

    /**
     * Test attribute "payment_expiry_date"
     */
    public function testPropertyPaymentExpiryDate()
    {
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "payment_method_name"
     */
    public function testPropertyPaymentMethodName()
    {
    }

    /**
     * Test attribute "late_penalty_rate"
     */
    public function testPropertyLatePenaltyRate()
    {
    }

    /**
     * Test attribute "shipping_total_ht"
     */
    public function testPropertyShippingTotalHt()
    {
    }

    /**
     * Test attribute "shipping_tva_rate"
     */
    public function testPropertyShippingTvaRate()
    {
    }

    /**
     * Test attribute "shipping_total_tva"
     */
    public function testPropertyShippingTotalTva()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "discount_total_ht"
     */
    public function testPropertyDiscountTotalHt()
    {
    }

    /**
     * Test attribute "discount_total_type"
     */
    public function testPropertyDiscountTotalType()
    {
    }

    /**
     * Test attribute "total_ht_nodiscount"
     */
    public function testPropertyTotalHtNodiscount()
    {
    }

    /**
     * Test attribute "total_ht"
     */
    public function testPropertyTotalHt()
    {
    }

    /**
     * Test attribute "total_ttc"
     */
    public function testPropertyTotalTtc()
    {
    }

    /**
     * Test attribute "total_tva"
     */
    public function testPropertyTotalTva()
    {
    }

    /**
     * Test attribute "vat_rates"
     */
    public function testPropertyVatRates()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "sale_date"
     */
    public function testPropertySaleDate()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "company_contact"
     */
    public function testPropertyCompanyContact()
    {
    }

    /**
     * Test attribute "company_siren"
     */
    public function testPropertyCompanySiren()
    {
    }

    /**
     * Test attribute "company_nic"
     */
    public function testPropertyCompanyNic()
    {
    }

    /**
     * Test attribute "company_share_capital"
     */
    public function testPropertyCompanyShareCapital()
    {
    }

    /**
     * Test attribute "company_commercial_court"
     */
    public function testPropertyCompanyCommercialCourt()
    {
    }

    /**
     * Test attribute "company_num_rcs"
     */
    public function testPropertyCompanyNumRcs()
    {
    }

    /**
     * Test attribute "company_num_trade_directory"
     */
    public function testPropertyCompanyNumTradeDirectory()
    {
    }

    /**
     * Test attribute "company_type"
     */
    public function testPropertyCompanyType()
    {
    }

    /**
     * Test attribute "company_address"
     */
    public function testPropertyCompanyAddress()
    {
    }

    /**
     * Test attribute "company_address_end"
     */
    public function testPropertyCompanyAddressEnd()
    {
    }

    /**
     * Test attribute "company_zip_code"
     */
    public function testPropertyCompanyZipCode()
    {
    }

    /**
     * Test attribute "company_city"
     */
    public function testPropertyCompanyCity()
    {
    }

    /**
     * Test attribute "company_country"
     */
    public function testPropertyCompanyCountry()
    {
    }

    /**
     * Test attribute "company_phone"
     */
    public function testPropertyCompanyPhone()
    {
    }

    /**
     * Test attribute "company_fax"
     */
    public function testPropertyCompanyFax()
    {
    }

    /**
     * Test attribute "company_email"
     */
    public function testPropertyCompanyEmail()
    {
    }

    /**
     * Test attribute "company_cgv"
     */
    public function testPropertyCompanyCgv()
    {
    }

    /**
     * Test attribute "company_include_cgv"
     */
    public function testPropertyCompanyIncludeCgv()
    {
    }

    /**
     * Test attribute "client_name"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "client_contact"
     */
    public function testPropertyClientContact()
    {
    }

    /**
     * Test attribute "client_address"
     */
    public function testPropertyClientAddress()
    {
    }

    /**
     * Test attribute "client_address_end"
     */
    public function testPropertyClientAddressEnd()
    {
    }

    /**
     * Test attribute "client_zip_code"
     */
    public function testPropertyClientZipCode()
    {
    }

    /**
     * Test attribute "client_city"
     */
    public function testPropertyClientCity()
    {
    }

    /**
     * Test attribute "client_country"
     */
    public function testPropertyClientCountry()
    {
    }

    /**
     * Test attribute "client_phone"
     */
    public function testPropertyClientPhone()
    {
    }

    /**
     * Test attribute "client_fax"
     */
    public function testPropertyClientFax()
    {
    }

    /**
     * Test attribute "client_email"
     */
    public function testPropertyClientEmail()
    {
    }

    /**
     * Test attribute "client_tva"
     */
    public function testPropertyClientTva()
    {
    }

    /**
     * Test attribute "client_dom"
     */
    public function testPropertyClientDom()
    {
    }

    /**
     * Test attribute "delivery_name"
     */
    public function testPropertyDeliveryName()
    {
    }

    /**
     * Test attribute "delivery_contact"
     */
    public function testPropertyDeliveryContact()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "delivery_address_end"
     */
    public function testPropertyDeliveryAddressEnd()
    {
    }

    /**
     * Test attribute "delivery_zip_code"
     */
    public function testPropertyDeliveryZipCode()
    {
    }

    /**
     * Test attribute "delivery_city"
     */
    public function testPropertyDeliveryCity()
    {
    }

    /**
     * Test attribute "delivery_country"
     */
    public function testPropertyDeliveryCountry()
    {
    }

    /**
     * Test attribute "delivery_phone"
     */
    public function testPropertyDeliveryPhone()
    {
    }

    /**
     * Test attribute "delivery_fax"
     */
    public function testPropertyDeliveryFax()
    {
    }

    /**
     * Test attribute "delivery_email"
     */
    public function testPropertyDeliveryEmail()
    {
    }

    /**
     * Test attribute "display_rules"
     */
    public function testPropertyDisplayRules()
    {
    }

    /**
     * Test attribute "style"
     */
    public function testPropertyStyle()
    {
    }

    /**
     * Test attribute "has_reduction"
     */
    public function testPropertyHasReduction()
    {
    }

    /**
     * Test attribute "signature"
     */
    public function testPropertySignature()
    {
    }

    /**
     * Test attribute "external_file"
     */
    public function testPropertyExternalFile()
    {
    }

    /**
     * Test attribute "external_url"
     */
    public function testPropertyExternalUrl()
    {
    }

    /**
     * Test attribute "payment_state"
     */
    public function testPropertyPaymentState()
    {
    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {
    }

    /**
     * Test attribute "total_nettopay"
     */
    public function testPropertyTotalNettopay()
    {
    }

    /**
     * Test attribute "fromquote"
     */
    public function testPropertyFromquote()
    {
    }

    /**
     * Test attribute "credit"
     */
    public function testPropertyCredit()
    {
    }

    /**
     * Test attribute "acompte"
     */
    public function testPropertyAcompte()
    {
    }

    /**
     * Test attribute "document_model"
     */
    public function testPropertyDocumentModel()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
